### PR TITLE
Migrate to v2

### PR DESCRIPTION
**Pull request by rickiesmooth**

### CODE REVIEW

**Comment by minheq** [comment]
@slorber please merge :)

**Comment by minheq** [comment]
@rickiesmooth i believe that u also need to change ES imports to CommonJS
https://www.gatsbyjs.org/docs/migrating-from-v1-to-v2/#convert-to-either-pure-commonjs-or-pure-es6

**Comment by slorber** [comment]
Hey thanks! didn't get any notification about your PR sorry for the delay

**Comment by slorber** [comment]
@minheq can you explain the problem with imports? Why not use ES imports everywhere instead of commonjs?

**Pull request merged**
